from pathlib import Path


def replace_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{label}: expected one patch context, got {count}")
    return text.replace(old, new, 1)


runner = Path("src/college_builder/pipeline/runner.py")
text = runner.read_text(encoding="utf-8")
text = replace_once(
    text,
    '''def _provider_usage_delta(before: ProviderUsage, after: ProviderUsage) -> ProviderUsage:\n    keys = set(before.provider_call_counts) | set(after.provider_call_counts)\n    calls = {\n        key: after.provider_call_counts.get(key, 0) - before.provider_call_counts.get(key, 0)\n        for key in keys\n        if after.provider_call_counts.get(key, 0) > before.provider_call_counts.get(key, 0)\n    }\n    return ProviderUsage(\n        provider_call_counts=calls,\n        cache_hits=max(0, after.cache_hits - before.cache_hits),\n        cache_misses=max(0, after.cache_misses - before.cache_misses),\n        latency_seconds=max(0.0, after.latency_seconds - before.latency_seconds),\n        tokens=max(0, after.tokens - before.tokens),\n        estimated_cost_usd=max(0.0, after.estimated_cost_usd - before.estimated_cost_usd),\n        fallback_count=max(0, after.fallback_count - before.fallback_count),\n        provider_errors=max(0, after.provider_errors - before.provider_errors),\n    )\n\n\ndef _merge_provider_usage(left: ProviderUsage, right: ProviderUsage) -> ProviderUsage:\n    calls = Counter(left.provider_call_counts)\n    calls.update(right.provider_call_counts)\n    return ProviderUsage(\n        provider_call_counts=dict(calls),\n        cache_hits=left.cache_hits + right.cache_hits,\n        cache_misses=left.cache_misses + right.cache_misses,\n        latency_seconds=left.latency_seconds + right.latency_seconds,\n        tokens=left.tokens + right.tokens,\n        estimated_cost_usd=left.estimated_cost_usd + right.estimated_cost_usd,\n        fallback_count=left.fallback_count + right.fallback_count,\n        provider_errors=left.provider_errors + right.provider_errors,\n    )\n''',
    '''def _optional_usage_delta(before: int | float | None, after: int | float | None):\n    if before is None or after is None:\n        return None\n    return max(0, after - before)\n\n\ndef _optional_usage_sum(left: int | float | None, right: int | float | None):\n    if left is None or right is None:\n        return None\n    return left + right\n\n\ndef _provider_usage_delta(before: ProviderUsage, after: ProviderUsage) -> ProviderUsage:\n    keys = set(before.provider_call_counts) | set(after.provider_call_counts)\n    calls = {\n        key: after.provider_call_counts.get(key, 0) - before.provider_call_counts.get(key, 0)\n        for key in keys\n        if after.provider_call_counts.get(key, 0) > before.provider_call_counts.get(key, 0)\n    }\n    return ProviderUsage(\n        provider_call_counts=calls,\n        cache_hits=max(0, after.cache_hits - before.cache_hits),\n        cache_misses=max(0, after.cache_misses - before.cache_misses),\n        latency_seconds=max(0.0, after.latency_seconds - before.latency_seconds),\n        tokens=_optional_usage_delta(before.tokens, after.tokens),\n        estimated_cost_usd=_optional_usage_delta(\n            before.estimated_cost_usd, after.estimated_cost_usd\n        ),\n        fallback_count=max(0, after.fallback_count - before.fallback_count),\n        provider_errors=max(0, after.provider_errors - before.provider_errors),\n    )\n\n\ndef _merge_provider_usage(left: ProviderUsage, right: ProviderUsage) -> ProviderUsage:\n    calls = Counter(left.provider_call_counts)\n    calls.update(right.provider_call_counts)\n    return ProviderUsage(\n        provider_call_counts=dict(calls),\n        cache_hits=left.cache_hits + right.cache_hits,\n        cache_misses=left.cache_misses + right.cache_misses,\n        latency_seconds=left.latency_seconds + right.latency_seconds,\n        tokens=_optional_usage_sum(left.tokens, right.tokens),\n        estimated_cost_usd=_optional_usage_sum(\n            left.estimated_cost_usd, right.estimated_cost_usd\n        ),\n        fallback_count=left.fallback_count + right.fallback_count,\n        provider_errors=left.provider_errors + right.provider_errors,\n    )\n''',
    "optional provider usage aggregation",
)
runner.write_text(text, encoding="utf-8", newline="\n")

report_tests = Path("tests/e2e/test_pipeline_report.py")
text = report_tests.read_text(encoding="utf-8")
text += '''\n\ndef test_provider_usage_delta_and_merge_preserve_unavailable_usage() -> None:\n    from college_builder.pipeline.runner import _merge_provider_usage, _provider_usage_delta\n\n    unknown = ProviderUsage(\n        provider_call_counts={"gate": 1},\n        cache_misses=1,\n        tokens=None,\n        estimated_cost_usd=None,\n    )\n    known = ProviderUsage(\n        provider_call_counts={"gate": 2},\n        cache_misses=2,\n        tokens=10,\n        estimated_cost_usd=0.25,\n    )\n\n    delta = _provider_usage_delta(unknown, known)\n    assert delta.tokens is None\n    assert delta.estimated_cost_usd is None\n\n    merged = _merge_provider_usage(known, unknown)\n    assert merged.tokens is None\n    assert merged.estimated_cost_usd is None\n\n\ndef test_provider_usage_delta_and_merge_keep_known_numeric_usage() -> None:\n    from college_builder.pipeline.runner import _merge_provider_usage, _provider_usage_delta\n\n    before = ProviderUsage(tokens=3, estimated_cost_usd=0.1)\n    after = ProviderUsage(tokens=11, estimated_cost_usd=0.4)\n    delta = _provider_usage_delta(before, after)\n    assert delta.tokens == 8\n    assert delta.estimated_cost_usd == 0.30000000000000004\n\n    merged = _merge_provider_usage(before, after)\n    assert merged.tokens == 14\n    assert merged.estimated_cost_usd == 0.5\n'''
report_tests.write_text(text, encoding="utf-8", newline="\n")
